### ISSUE TITLE
mongodb_store_cpp_client fails when testing for release

### ISSUE THREAD

**Issue by Jailander** [strands-project/strands_navigation#87]
Hi I think 'mongodb_store_cpp_client' has to be removed from dependencies on message_store_map_switcher @hawesie is this right?

**Comment by hawesie** [comment]
Yes, remove it.

**Comment by Jailander** [comment]
done via #88 waiting for merge

**Comment by cdondrup** [comment]
Actually the `mongodb_store_cpp_client` has to be replaced by `mongodb_store` because the cpp client still exists but has been moved. @Jailander please check your PR to make sure that you not just remove it but replace it where the client is still used.

**Comment by Jailander** [comment]
just fixed it and test it should work now

**Comment by cdondrup** [comment]
Thank you.
